### ISSUE TITLE
Create wireframe for new UX feature (FE)

### ISSUE THREAD

**Issue by ckccameron** [AngelaGuardia/Crate#18]

**Comment by holladayian** [comment]
[Crate excalidraw](https://excalidraw.com/#room=2552cd0aa1ac1486fd6d,RlbElgtDohW3VbwRhMRCyg)

**Comment by holladayian** [comment]
Original update to `/user/profile`
![Screen Shot 2020-12-05 at 12 59 14 PM](https://user-images.githubusercontent.com/62005294/101266271-b23c8780-36f9-11eb-80bb-504ffc162c84.png)

2nd update to `/user/profile`
![Screen Shot 2020-12-05 at 1 01 19 PM](https://user-images.githubusercontent.com/62005294/101266294-faf44080-36f9-11eb-97ae-ef22e5436ce5.png)

Addition for `/user/history`
![Screen Shot 2020-12-05 at 1 02 06 PM](https://user-images.githubusercontent.com/62005294/101266309-165f4b80-36fa-11eb-86d9-9e4ee0d82db2.png)
